#! /bin/sh

### BEGIN INIT INFO
# Provides:		https
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	https server
### END INIT INFO

cd /home/bee/html/cgi/socket/
./start
echo hello > test.txt

