#! /bin/sh

### BEGIN INIT INFO
# Provides:		https
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	https server
### END INIT INFO

cd /home/bee/bee.fish/cgi/socket/
./start /home/bee/bee.fish
echo hello > test.txt

#run this to load it to be run at start up
#cd /etc/init.d
#sudo update-rc.d https defaults