#!/bin/bash

echo "$0 should be run as the bee user"

base=~/bee.fish/cgi/socket
echo  $base

pwd >> $base/start.log
whoami >> $base/start.log

echo "Stopping..."
$base/stop

echo "Starting..."

$base/http-server 80  &
echo $! >> $base/http-server.pid

$base/secure/https-server ~/bee.fish 4 &
echo $! >> $base/https-server.pid

