#!/bin/bash

cd "$(dirname "$0")"

echo "Stopping..."
./stop

echo "Starting..."

./server.bin 80  >> http.log 2>&1 &
echo $! >> http.pid
./secure/server.bin /home/bee/html >> https.log 2>&1 &
echo $! >> https.pid
