#!/bin/bash

cd "$(dirname "$0")"

pwd >> start.log
whoami >> start.log

echo "Stopping..."
./stop

echo "Starting..."

./http-server 80  >> http-server.log 2>&1 &
echo $! >> http-server.pid

./secure/https-server /home/bee/bee.fish >> https-server.log 2>&1 &
echo $! >> https-server.pid
