all:
	make -C args
	make -C interprocess-lock
	make -C parser
	make -C database
	make -C server
	
clean:
	make -C args clean
	make -C interprocess-lock clean
	make -C parser clean
	make -C database clean
	make -C server clean
	
