#!/bin/bash

echo "$0 should be run as the sudo user"

base=/home/bee/bee.fish
echo  $base
cd $base

pwd >> $base/start.log
whoami >> $base/start.log

echo "Stopping..."
cgi/node/stop

echo "Starting..."

sudo node --experimental-modules cgi/node/server.js &
echo $! >> cgi/node/server.pid

