#!/bin/bash

echo "$0 restarts server"

base=/home/bee/bee.fish
message="Serving files from $base"
echo $message

cd $base

echo $message >> $base/../start.log
whoami >> $base/../start.log

echo "Stopping..."
cgi/node/stop

echo "Starting..."

sudo node cgi/node/server.js &
echo $! >> cgi/node/server.pid

