#include "camera_pins.h"

const esp32cam::Pins M5Timer {
  D0: Y2_GPIO_NUM,
  D1: Y3_GPIO_NUM,
  D2: Y4_GPIO_NUM,
  D3: Y5_GPIO_NUM,
  D4: Y6_GPIO_NUM,
  D5: Y7_GPIO_NUM,
  D6: Y8_GPIO_NUM,
  D7: Y9_GPIO_NUM,
  XCLK:  XCLK_GPIO_NUM,
  PCLK: PCLK_GPIO_NUM,
  VSYNC: VSYNC_GPIO_NUM,
  HREF: HREF_GPIO_NUM,
  SDA: SIOD_GPIO_NUM,
  SCL: SIOC_GPIO_NUM,
  RESET: RESET_GPIO_NUM,
  PWDN: PWDN_GPIO_NUM,
};
